import type { Metadata } from "next";

import { LegalShell } from "@/components/legal-shell";
import { SITE_TITLE } from "@/lib/site-brand";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: `Terms for using ${SITE_TITLE}.`,
};

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Use">
      <p>Last updated: August 6, 2026</p>
      <p>
        By using {SITE_TITLE} at fighur.ai or in our mobile apps, you agree to these Terms of Use.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">1. The service</h2>
      <p>
        {SITE_TITLE} is an AI assistant platform for chat, agents, apps, and related tools. Features
        may change. We may suspend or discontinue access for abuse, non-payment, or operational
        reasons.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">2. Accounts</h2>
      <p>
        You are responsible for your account credentials and for activity under your account. Provide
        accurate information. You must be old enough to form a binding contract in your region (and
        at least 13).
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">3. Acceptable use</h2>
      <ul className="list-disc space-y-2 pl-5">
        <li>Do not break the law, harm others, or attempt to abuse or reverse-engineer the service.</li>
        <li>Do not upload malware or attempt unauthorized access to systems or other users’ data.</li>
        <li>
          Do not use the service to generate content you intend to present as solely human-authored
          where disclosure is required by law or platform rules.
        </li>
      </ul>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">4. AI outputs</h2>
      <p>
        Model outputs can be wrong, incomplete, or inappropriate. You are responsible for reviewing
        results before relying on them. Outputs may be generated by third-party AI providers. We do
        not guarantee accuracy, uniqueness, or fitness for a particular purpose.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">5. Subscriptions & billing</h2>
      <p>
        Paid plans may be sold via web checkout (e.g. Stripe) and/or Apple In-App Purchase in the iOS
        app. Apple’s terms apply to purchases made through the App Store. Fees are described at
        purchase time. Unused quotas generally do not roll over unless we say otherwise.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">6. Your content</h2>
      <p>
        You retain rights to content you submit. You grant us a limited license to host, process, and
        transmit that content solely to operate the service (including sending it to AI providers you
        use). Do not submit content you lack rights to.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">7. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED “AS IS” WITHOUT WARRANTIES OF ANY KIND, TO THE FULLEST EXTENT
        PERMITTED BY LAW. WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
        ARISING FROM USE OF THE SERVICE.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">8. Contact</h2>
      <p>
        <a className="text-[var(--accent)] underline" href="mailto:hello@fighurai.com">
          hello@fighurai.com
        </a>{" "}
        ·{" "}
        <a className="text-[var(--accent)] underline" href="/support">
          Support
        </a>{" "}
        ·{" "}
        <a className="text-[var(--accent)] underline" href="/privacy">
          Privacy Policy
        </a>
      </p>
    </LegalShell>
  );
}
