import type { Metadata } from "next";

import { LegalShell } from "@/components/legal-shell";
import { SITE_TITLE } from "@/lib/site-brand";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: `Terms for using ${SITE_TITLE}.`,
};

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Use">
      <p>Last updated: August 11, 2026</p>
      <p className="text-[0.7rem] text-[var(--text-faint)]">
        Have qualified counsel review these terms for your jurisdiction before relying on them in a
        dispute.
      </p>
      <p>
        By using {SITE_TITLE} at fighur.ai, our mobile apps, APIs, or the FIGHURAI Colors browser
        extension, you agree to these Terms of Use and our{" "}
        <a className="text-[var(--accent)] underline" href="/privacy">
          Privacy Policy
        </a>
        . The extension is also governed by the{" "}
        <a className="text-[var(--accent)] underline" href="/eula">
          Extension EULA
        </a>
        .
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">1. The service</h2>
      <p>
        {SITE_TITLE} is an AI assistant platform for chat, agents, apps, browser tools (including
        Colors), and related features. Features may change. We may suspend or discontinue access for
        abuse, non-payment, or operational reasons.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">
        2. Ownership & intellectual property
      </h2>
      <p>
        The service, software, documentation, branding, and extensions are owned by {SITE_TITLE}{" "}
        and/or its affiliates. Except for the limited license below, no rights are transferred to
        you. You may not copy, sell, sublicense, or redistribute our software or branding except as
        expressly allowed in these Terms or a separate written license.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">3. License to you</h2>
      <p>
        We grant you a limited, personal, non-exclusive, non-transferable, revocable license to use
        the service for your own lawful purposes while your account is in good standing. Paid
        features (including Pro and the Colors extension) require an active eligible subscription or
        other access we grant.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">4. Accounts</h2>
      <p>
        You are responsible for your account credentials and for activity under your account. Provide
        accurate information. You must be old enough to form a binding contract in your region (and
        at least 13).
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">5. Acceptable use</h2>
      <ul className="list-disc space-y-2 pl-5">
        <li>Do not break the law, harm others, or attempt to abuse or reverse-engineer the service.</li>
        <li>Do not upload malware or attempt unauthorized access to systems or other users’ data.</li>
        <li>
          Do not use the service to generate content you intend to present as solely human-authored
          where disclosure is required by law or platform rules.
        </li>
        <li>Do not bypass plan limits, entitlement checks, or payment systems.</li>
      </ul>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">6. AI outputs</h2>
      <p>
        Model outputs can be wrong, incomplete, or inappropriate. You are responsible for reviewing
        results before relying on them. Outputs may be generated by third-party AI providers. We do
        not guarantee accuracy, uniqueness, or fitness for a particular purpose.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">
        7. Subscriptions & billing
      </h2>
      <p>
        Paid plans (including Pro) may be sold via web checkout (e.g. Stripe) and/or Apple In-App
        Purchase in the iOS app. Apple’s terms apply to purchases made through the App Store. Fees
        are described at purchase time. Unused quotas generally do not roll over unless we say
        otherwise. Pro may unlock additional tools such as the Colors Chrome extension; availability
        can change.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">8. Your content</h2>
      <p>
        You retain rights to content you submit. You grant us a limited license to host, process, and
        transmit that content solely to operate the service (including sending it to AI providers you
        use). Do not submit content you lack rights to.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">9. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED “AS IS” WITHOUT WARRANTIES OF ANY KIND, TO THE FULLEST EXTENT
        PERMITTED BY LAW. WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
        ARISING FROM USE OF THE SERVICE.
      </p>

      <h2 className="pt-2 text-base font-semibold text-[var(--text-primary)]">10. Contact</h2>
      <p>
        <a className="text-[var(--accent)] underline" href="mailto:hello@fighurai.com">
          hello@fighurai.com
        </a>{" "}
        ·{" "}
        <a className="text-[var(--accent)] underline" href="/support">
          Support
        </a>{" "}
        ·{" "}
        <a className="text-[var(--accent)] underline" href="/privacy">
          Privacy Policy
        </a>{" "}
        ·{" "}
        <a className="text-[var(--accent)] underline" href="/legal">
          Own &amp; sell checklist
        </a>
      </p>
    </LegalShell>
  );
}
